import sys
import os


def OilGenTemplate(args):
    # Generate template
    OilTemplateFile = open(args.template_oil_file, 'w', encoding='utf-8')
    OilTemplateFile.write("// OIL-Definition-File\n")
    OilTemplateFile.write("OIL_VERSION = \"2.3\";\n")
    OilTemplateFile.write("\n")
    OilTemplateFile.write("CPU CPU_NAME {\n")
    OilTemplateFile.write("\n")
    OilTemplateFile.write("   OS OS_NAME {\n")
    OilTemplateFile.write("      STARTUPHOOK = TRUE;\n")
    OilTemplateFile.write("      ERRORHOOK = TRUE;\n")
    OilTemplateFile.write("      SHUTDOWNHOOK = TRUE;\n")
    OilTemplateFile.write("      PRETASKHOOK = TRUE;\n")
    OilTemplateFile.write("      POSTTASKHOOK = TRUE;\n")
    OilTemplateFile.write("      WithStackCheck = TRUE;\n")
    OilTemplateFile.write("      CpuFrequency = 16000000;\n")
    OilTemplateFile.write("      MaximumVectorEntries = 113;\n")
    OilTemplateFile.write("      TickTime = 1000;\n")
    OilTemplateFile.write("   };\n")
    OilTemplateFile.write("\n")
    OilTemplateFile.write("   TASK OSTASK_TASK01 {\n")
    OilTemplateFile.write("      TYPE = AUTO;\n")
    OilTemplateFile.write("      SCHEDULE = FULL;\n")
    OilTemplateFile.write("      PRIORITY = 50;\n")
    OilTemplateFile.write("      ACTIVATION = 1;\n")
    OilTemplateFile.write("      AUTOSTART = TRUE;\n")
    OilTemplateFile.write("      EVENT = OSEVT_EVENT01;\n")
    OilTemplateFile.write("      EVENT = OSEVT_EVENT02;\n")
    OilTemplateFile.write("      EVENT = OSEVT_EVENT03;\n")
    OilTemplateFile.write("      RESOURCE = OSRES_RESOURCE01;\n")
    OilTemplateFile.write("      RESOURCE = OSRES_RESOURCE02;\n")
    OilTemplateFile.write("      StackSize = 0x800;\n")
    OilTemplateFile.write("   };\n")
    OilTemplateFile.write("   \n")
    OilTemplateFile.write("   TASK OSTASK_TASK02 {\n")
    OilTemplateFile.write("      TYPE = AUTO;\n")
    OilTemplateFile.write("      SCHEDULE = FULL;\n")
    OilTemplateFile.write("      PRIORITY = 5;\n")
    OilTemplateFile.write("      ACTIVATION = 1;\n")
    OilTemplateFile.write("      AUTOSTART = TRUE;\n")
    OilTemplateFile.write("      EVENT = OSEVT_EVENT03;\n")
    OilTemplateFile.write("      EVENT = OSEVT_EVENT02;\n")
    OilTemplateFile.write("      EVENT = OSEVT_EVENT01;\n")
    OilTemplateFile.write("      RESOURCE = OSRES_RESOURCE02;\n")
    OilTemplateFile.write("      RESOURCE = OSRES_RESOURCE01;\n")
    OilTemplateFile.write("      StackSize = 800;\n")
    OilTemplateFile.write("   };\n")
    OilTemplateFile.write("\n")
    OilTemplateFile.write("   ALARM OSALARM_ALARM01 {\n")
    OilTemplateFile.write("      ACTION = SETEVENT\n")
    OilTemplateFile.write("      {\n")
    OilTemplateFile.write("         TASK = OSTASK_TASK01;\n")
    OilTemplateFile.write("         EVENT = OSEVT_EVENT01;\n")
    OilTemplateFile.write("      };\n")
    OilTemplateFile.write("      AUTOSTART = FALSE;\n")
    OilTemplateFile.write("   };\n")
    OilTemplateFile.write("\n")
    OilTemplateFile.write("   ALARM OSALARM_ALARM02 {\n")
    OilTemplateFile.write("      ACTION = ACTIVATETASK\n")
    OilTemplateFile.write("      {\n")
    OilTemplateFile.write("         TASK = OSTASK_TASK02;\n")
    OilTemplateFile.write("      };\n")
    OilTemplateFile.write("      AUTOSTART = FALSE;\n")
    OilTemplateFile.write("   };\n")
    OilTemplateFile.write("\n")
    OilTemplateFile.write("   ALARM OSALARM_ALARM03 {\n")
    OilTemplateFile.write("      ACTION = ALARMCALLBACK\n")
    OilTemplateFile.write("      {\n")
    OilTemplateFile.write("         ALARMCALLBACKNAME = \"OsTickTimerCallback\";\n")
    OilTemplateFile.write("      };\n")
    OilTemplateFile.write("      AUTOSTART = TRUE\n")
    OilTemplateFile.write("      {\n")
    OilTemplateFile.write("         ALARMTIME = 0;\n")
    OilTemplateFile.write("         CYCLETIME = 5;\n")
    OilTemplateFile.write("      };\n")
    OilTemplateFile.write("   };\n")
    OilTemplateFile.write("\n")
    OilTemplateFile.write("   EVENT OSEVT_EVENT01 {\n")
    OilTemplateFile.write("      MASK = 0x80;\n")
    OilTemplateFile.write("   };\n")
    OilTemplateFile.write("\n")
    OilTemplateFile.write("   EVENT OSEVT_EVENT02 {\n")
    OilTemplateFile.write("      MASK = AUTO;\n")
    OilTemplateFile.write("   };\n")
    OilTemplateFile.write("\n")
    OilTemplateFile.write("   EVENT OSEVT_EVENT03 {\n")
    OilTemplateFile.write("      MASK = AUTO;\n")
    OilTemplateFile.write("   };\n")
    OilTemplateFile.write("\n")
    OilTemplateFile.write("   RESOURCE OSRES_RESOURCE01 {\n")
    OilTemplateFile.write("      RESOURCEPROPERTY = STANDARD;\n")
    OilTemplateFile.write("   };\n")
    OilTemplateFile.write("\n")
    OilTemplateFile.write("   RESOURCE OSRES_RESOURCE02 {\n")
    OilTemplateFile.write("      RESOURCEPROPERTY = STANDARD;\n")
    OilTemplateFile.write("   };\n")
    OilTemplateFile.write("\n")
    OilTemplateFile.write("   ISR ISR_000 {\n")
    OilTemplateFile.write("      CATEGORY = 2;\n")
    OilTemplateFile.write("      VectorAddress = 0;\n")
    OilTemplateFile.write("   };\n")
    OilTemplateFile.write("\n")
    OilTemplateFile.write("   ISR ISR_001 {\n")
    OilTemplateFile.write("      CATEGORY = 2;\n")
    OilTemplateFile.write("      VectorAddress = 1;\n")
    OilTemplateFile.write("   };\n")
    OilTemplateFile.write("\n")
    OilTemplateFile.write("};\n")
    OilTemplateFile.close()
