// **********************************************************************************************************************
//                                            OSEK OS PRIORITY LEVELS                                             
// **********************************************************************************************************************
// Note: This file is automatically generated from the Excel file OsekCfg.xlsm, Please do not modify it manually !
// **********************************************************************************************************************

// **********************************************************************************************************************
// Filename        : osGenPrioTypes.h
// 
// Author          : Chalandi Amine
//
// Owner           : Chalandi Amine
// 
// Excel File      : D:\GHS_PRJ\MyOSEK\Osek_Renesas\SW\OSEK\HwPlatform\Renesas\F1x\R7F701035\Generator\OsekCfg.xlsm
// 
// Generation Date : February 21, 2020 16:20
// 
// Description     : OS Priority Levels
// 
// **********************************************************************************************************************

#ifndef _OSPRIOTYPES_H_
#define _OSPRIOTYPES_H_


typedef struct
{
  unsigned long OsGroupPrioLevel1; /* PRIORITY 0 --> 31 */
}OsSchedPrioType;



#endif

