name: Baremetal_Pico2_dual_core_nosdk

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  target-gcc-arm-none-eabi:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Install ARM Toolchain v13.3
        run: |
          sudo mkdir -p /arm-toolchain
          wget https://developer.arm.com/-/media/Files/downloads/gnu/13.3.rel1/binrel/arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-eabi.tar.xz
          sudo tar -xf arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-eabi.tar.xz -C /arm-toolchain

      - name: Verify Toolchain Installation
        run: |
          sudo ls -la /arm-toolchain/arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-eabi/bin
          sudo find /arm-toolchain -name arm-none-eabi-gcc

      - name: Add ARM Toolchain to PATH
        run: |
          echo "ARM_TOOLCHAIN=/arm-toolchain/arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-eabi/bin" >> $GITHUB_ENV
          echo "PATH=$ARM_TOOLCHAIN:$PATH" >> $GITHUB_ENV

      - name: Verify PATH and Check arm-none-eabi-gcc
        run: |
          echo "Current PATH: $PATH"
          echo "ARM_TOOLCHAIN: $ARM_TOOLCHAIN"
          which arm-none-eabi-gcc || echo "arm-none-eabi-gcc not found"

      - name: Verify PATH in a New Step
        run: |
          echo "Updated PATH: $PATH"
          which arm-none-eabi-gcc || echo "arm-none-eabi-gcc not found"

      - name: Run Rebuild with Absolute Path
        run: |
          /arm-toolchain/arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc --version
          cd ./Build
          make clean all CORE_FAMILY=ARM
