name: Baremetal_Pico2_dual_core_nosdk

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  target-gcc-arm-none-eabi:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          
      - name: Install ARM Toolchain v13.3
        run: |
          wget https://developer.arm.com/-/media/Files/downloads/gnu/13.3.rel1/binrel/arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-eabi.tar.xz
          mkdir ~/arm-toolchain
          tar -xf arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-eabi.tar.xz -C ~/arm-toolchain

      - name: Add ARM Toolchain to PATH
        run: echo "PATH=~/arm-toolchain/arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-eabi/bin:$PATH" >> $GITHUB_ENV

      - name: Verify PATH change
        run: echo $PATH

      - name: Query Compiler Version
        run: arm-none-eabi-g++ -v

      - name: Rebuild Blinky
        run: |
          mv ./Tools/picotool/picotool_linux ./Tools/picotool/picotool
          cd ./Build
          bash ./Rebuild.sh ARM

      - name: List Output Files
        run: |
          ls -la ../Output/Baremetal_Pico2_dual_core_nosdk.elf
          ls -la ../Output/Baremetal_Pico2_dual_core_nosdk.uf2
