name: Baremetal_Pico2_dual_core_nosdk

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  target-gcc-arm-none-eabi:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Install ARM Toolchain v13.3
        run: |
          wget https://developer.arm.com/-/media/Files/downloads/gnu/13.3.rel1/binrel/arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-eabi.tar.xz
          mkdir -p ~/arm-toolchain
          tar -xf arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-eabi.tar.xz -C ~/arm-toolchain

      - name: Verify Toolchain Installation
        run: ls -la ~/arm-toolchain/arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-eabi/bin

      - name: Add ARM Toolchain to PATH
        run: echo "PATH=~/arm-toolchain/arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-eabi/bin:$PATH" >> $GITHUB_ENV

      - name: Verify PATH and Run Rebuild
        run: |
          echo "Current PATH: $PATH"
          echo "Checking if arm-none-eabi-gcc is available"
          which arm-none-eabi-gcc
          cd ./Build
          chmod +x ./Rebuild.sh
          ./Rebuild.sh ARM
